[build]
  command = "npm run build"
  publish = ".next"
  environment = { 
    NODE_VERSION = "18.17.0",
    NEXT_PUBLIC_API_URL = "https://api.example.com"  # Replace with your actual API URL
  }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-cache-killer"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 